 name: Aliyun Signin
 
 on:
   schedule:
     # 每天国际时间 17:20 运行一次, 中国时间 01:20
     - cron: '20 17 * * *'
   workflow_dispatch:
 jobs:
   signin:
     name: Aliyun Signin
     runs-on: ubuntu-latest
     steps:
       - uses: ImYrS/aliyun-auto-signin@v1.3.2
         with:
           REFRESH_TOKENS: ${{ 1ef3897c475e45e991b97fcfd152b927 }}
           PUSH_TYPES: 'telegram,smtp'
           SERVERCHAN_SEND_KEY: ${{ SCT124157TXVHQuTKbG3sIgBVPaFeQNN36 }}
           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
           PUSHPLUS_TOKEN: ${{ 1eca33b6b9c54afb9971fc76b37a782e }}
           SMTP_HOST: ${{ secrets.SMTP_HOST }}
           SMTP_PORT: ${{ secrets.SMTP_PORT }}
           SMTP_TLS: ${{ secrets.SMTP_TLS }}
           SMTP_USER: ${{ secrets.SMTP_USER }}
           SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
           SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
           SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
